server:
    port: 8080



spring:
    thymeleaf:
        prefix: classpath:/templates/views/
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db907?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: user907
        password: 1234
    security:
        user:
            name: user1
            password: 1234
    mybatis:
        mapper-locations: classpath:mapper/**/*.xml
    app:
        upload:
            path: upload
    pagination:
        write_pages: 10
        page_rows: 10



google:
    maps:
        api:
            key: AIzaSyA9awHEvUkCV6_CBwjTekEnILebtwOi8ps
